# Generated by Django 5.1.2 on 2024-10-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
