# Generated by Django 5.1.2 on 2024-12-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0002_alter_animal_age_alter_animal_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caretaker",
            options={"ordering": ["username"]},
        ),
    ]
